# config.py — Centralized configuration for molviz-app

# Default molecule input
DEFAULT_SMILES = "CCO"  # Ethanol

# PDF export settings
PDF_FILENAME = "geometry_report.pdf"
PDF_TITLE = "Molecular Geometry Report"
PDF_FOOTER = "Generated by molviz-app"

# Viewer settings
VIEWER_WIDTH = 600
VIEWER_HEIGHT = 400
VIEWER_STYLE = {'stick': {}}

# UI layout
PAGE_TITLE = "Molecular Geometry Visualizer"
LAYOUT = "wide"

# Font settings for PDF
FONT_TITLE = ("Helvetica-Bold", 16)
FONT_META = ("Helvetica", 10)
FONT_SECTION = ("Helvetica-Bold", 12)
FONT_BODY = ("Helvetica", 11)
FONT_FOOTER = ("Helvetica-Oblique", 9)

# Geometry formatting
ANGLE_FORMAT = "{:.2f}°"
LENGTH_FORMAT = "{:.2f} Å"
