from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from datetime import datetime
from app.config import DEFAULT_SMILES, PDF_FILENAME, PAGE_TITLE # noqa


def export_geometry_pdf(filename: str, geometry_data: dict, smiles: str):
    """
    Exports molecular geometry details to a simple annotated PDF.
    """
    try:
        c = canvas.Canvas(filename, pagesize=letter)
        width, height = letter

        # Title
        c.setFont("Helvetica-Bold", 16)
        c.drawString(50, height - 50, "Molecular Geometry Report")

        # Metadata
        c.setFont("Helvetica", 10)
        c.drawString(50, height - 70, f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        c.drawString(50, height - 85, f"SMILES: {smiles}")

        # Geometry Details
        c.setFont("Helvetica-Bold", 12)
        c.drawString(50, height - 120, "Geometry Summary:")
        c.setFont("Helvetica", 11)

        # Format angles and lengths with clearer variable names
        formatted_angles = ', '.join([f"{bond_angle:.2f}°" for bond_angle in geometry_data['angles']])
        formatted_lengths = ', '.join([f"{bond_length:.2f} Å" for bond_length in geometry_data['lengths']])

        c.drawString(70, height - 140, f"Geometry Type: {geometry_data['geometry']}")
        c.drawString(70, height - 160, f"Bond Angles: {formatted_angles}")
        c.drawString(70, height - 180, f"Bond Lengths: {formatted_lengths}")

        # Footer
        c.setFont("Helvetica-Oblique", 9)
        c.drawString(50, 30, "Generated by molviz-app")

        c.save()
        return True

    except Exception as e:
        print(f"PDF export failed: {e}")
        return False
